<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_WebElement</name>
   <tag></tag>
   <elementGuidId>3b73cc3a-eb95-4ae1-8c25-6066de934c1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'WebElement')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fa7c05f7-eec7-4d24-9741-fb98905b62ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>WebElement.html</value>
      <webElementGuid>a5cc8210-0c89-406b-b36b-0cedd533f901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>interface in org.openqa.selenium</value>
      <webElementGuid>46c04d2c-58ca-4288-94fc-cf8cf9b9e775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WebElement</value>
      <webElementGuid>aa797bb5-d567-498b-a34a-1363cb9622f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;contentContainer&quot;]/ul[@class=&quot;blockList&quot;]/li[@class=&quot;blockList&quot;]/table[@class=&quot;typeSummary&quot;]/tbody[2]/tr[@class=&quot;rowColor&quot;]/th[@class=&quot;colFirst&quot;]/a[1]</value>
      <webElementGuid>8b1dc09d-2f4e-4581-9c9e-abeb4001b2ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'WebElement')]</value>
      <webElementGuid>8e9e9ff3-0f95-4942-954f-bbb6f08d4ea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Describes, in general terms, a webdriver instance.'])[1]/following::a[1]</value>
      <webElementGuid>6317c9f5-bdd3-4cd8-9061-4c23be106b42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WebDriverInfo'])[1]/following::a[1]</value>
      <webElementGuid>dcc18c53-8cc5-4282-8650-bf7fa00b54a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Represents an HTML element.'])[1]/preceding::a[1]</value>
      <webElementGuid>5355b1c1-b7d4-46fd-8dd7-6a4969799801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WrapsDriver'])[1]/preceding::a[1]</value>
      <webElementGuid>f5e41dbb-d3ed-44b5-975f-1de183d300e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WebElement']/parent::*</value>
      <webElementGuid>17096240-953b-43fe-821a-c21a152dde91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'WebElement.html')]</value>
      <webElementGuid>33b6e336-9131-4b58-84d9-7bfbf470f30a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[22]/th/a</value>
      <webElementGuid>dfee135a-368c-41a5-92e3-0fbd048f9e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'WebElement.html' and @title = 'interface in org.openqa.selenium' and (text() = 'WebElement' or . = 'WebElement')]</value>
      <webElementGuid>4137ad15-70df-4d10-a10d-be3aa5213d1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
